### PR TITLE
protoc-gen-openapi/jsonschema: Add support for string-based enums

### PR DESCRIPTION
**Pull request by adolfo**
This change exposes a configuration option that enables Protobuf enums to be compiled to enums with the underlying type of `string`.

The following Protobuf message:
```protobuf
message Message {
  Kind kind = 1;
}

enum Kind {
  KIND_UNSPECIFIED = 0;
  KIND_1 = 1;
  KIND_2 = 2;
}
```

Will be compiled to the following OpenAPI spec:
```yaml
Message:
  type: object
  properties:
      kind:
          format: enum
          type: string
          enum:
              - KIND_UNSPECIFIED
              - KIND_1
              - KIND_2
```

And will be compiled to the following jsonschema spec:
```json
{
  "title": "Message",
  "$id": "http://example.com/schemas/Message.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "kind": {
      "title": "kind",
      "type": "string",
      "enum": [
        "KIND_UNSPECIFIED",
        "KIND_1",
        "KIND_2"
      ],
      "format": "enum"
    }
  }
}
```

To enable string serialization, pass the `enum_type` flag:

```bash
$ protoc sample.proto -I. --openapi_out=enum_type=string:.
```

```bash
$ protoc sample.proto -I. --jsonschema_out=enum_type=string:.
```
The existing enum behavior remains unchanged and defaults to `integer` when the `enum_type` flag is not provided.

### CODE REVIEW

**Comment by morphar** [comment]
Nice! Thank you :)
Do you know if Envoy would accept this form? Or is this meant for another JSON transcoder?

LGTM @timburks

**Comment by adolfo** [comment]
@morphar Yes, Envoy will pass these string enum values through to the gRPC service and even validate them.

I'm also using the compiled OpenAPI spec to generate a web client (using openapi-generator) that uses these enum values to create language-specific enum values (Elm). Working well so far.

**Comment by morphar** [comment]
@adolfo Very nice! :)
I really like the idea of using strings instead of ints in the REST layer. I will definitely give this a try in my own setup.

**Review by timburks — APPROVED** [review]
Deferring to @morphar's LGTM - thanks for adding this!

**Pull request merged**
